### ISSUE TITLE
Unresolved import `iced::Alignment`

### ISSUE THREAD

**Issue by avi-cenna** [iced-rs/iced#1128]
Hello,

I am experimenting with Iced, and I ran into a bit of an issue when trying to use the Counter example.

I received the following error:

```
error[E0432]: unresolved import `iced::Alignment`
 --> src/main.rs:4:5
  |
4 |     Alignment,
  |     ^^^^^^^^^ no `Alignment` in the root
```

My `Cargo.toml` is as follows, and I was copying the code directly from the example in GitHub.

```toml
[package]
name = "iced_experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"
```

I think this issue originates somewhere in the `iced-core` package, as it seems there is a discrepancy between what's in GitHub and what is being downloaded locally by Cargo. Locally, I have the file `align.rs` and if I change `Alignment` to `Align` it works, but on GitHub it looks like the file has been renamed to `alignment.rs` and `Align` has been renamed to `Alignment`.
