### ISSUE TITLE
Linking error when cross compiling to x86_64-pc-windows-gnu from 

### ISSUE THREAD

**Issue by FuzzyLitchi** [iced-rs/iced#2107]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When I run `cargo build --target x86_64-pc-windows-gnu` it fails to compile the project.

This is the output (truncated, the original is 18430 lines long): https://gist.github.com/FuzzyLitchi/ff491fa3de36c932ebe701ce6b81938a

The project looks like this. I've tried to slim it down a bit.

main.rs:
```rs
use color_eyre::Result;

mod app;

use app::Example;
use iced::{Application, Settings};

pub fn main() -> Result<(), ()> {
    Example::run(Settings::default()).unwrap();

    Ok(())
}
```
app.rs
```rs
use iced::executor;
use iced::font::{self, Font};
use iced::widget::{checkbox, column, container, text};
use iced::{Application, Command, Element, Length, Theme};

const ICON_FONT: Font = Font::with_name("icons");

#[derive(Default)]
pub struct Example {
    default_checkbox: bool,
    custom_checkbox: bool,
}

#[derive(Debug, Clone, Copy)]
pub enum Message {
    DefaultChecked(bool),
    CustomChecked(bool),
    FontLoaded(Result<(), font::Error>),
}

impl Application for Example {
    type Message = Message;
    type Flags = ();
    type Executor = executor::Default;
    type Theme = Theme;

    fn new(_flags: Self::Flags) -> (Self, Command<Message>) {
        (
            Self::default(),
            font::load(include_bytes!("../icons.ttf").as_slice()).map(Message::FontLoaded),
        )
    }

    fn title(&self) -> String {
        String::from("Name")
    }

    fn update(&mut self, message: Message) -> Command<Message> {
        match message {
            Message::DefaultChecked(value) => self.default_checkbox = value,
            Message::CustomChecked(value) => self.custom_checkbox = value,
            Message::FontLoaded(_) => (),
        }

        Command::none()
    }

    fn view(&self) -> Element<Message> {
        let default_checkbox = checkbox("Default", self.default_checkbox, Message::DefaultChecked);
        let custom_checkbox = checkbox("Custom", self.custom_checkbox, Message::CustomChecked)
            .icon(checkbox::Icon {
                font: ICON_FONT,
                code_point: '\u{e901}',
                size: None,
                line_height: text::LineHeight::Relative(1.0),
                shaping: text::Shaping::Basic,
            });

        let content = column![default_checkbox, custom_checkbox].spacing(22);

        container(content)
            .width(Length::Fill)
            .height(Length::Fill)
            .center_x()
            .center_y()
            .into()
    }
}
```
Cargo.toml
```toml
[package]
name = "fucklinkers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.10", features = ["async-std", "debug"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.15"
color-eyre = "0.6.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
thiserror = "1.0.49"
lazy_static = "1.4.0"
async-std = "1.0"
directories-next = "2.0"
```

### What is the expected behavior?

I was expecting it to compile.

### Version

crates.io release

### Operating System

Linux

### Do you have any log output?

```shell
$ cargo --version --verbose
cargo 1.72.1 (103a7ff2e 2023-08-15)
release: 1.72.1
commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
commit-date: 2023-08-15
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Arch Linux [64-bit]
```
