### ISSUE TITLE
Problem rendering texts in PopOS 22.04

### ISSUE THREAD

**Issue by soucosmo** [iced-rs/iced#2367]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

My development environment
![My development environment](https://github.com/iced-rs/iced/assets/14854891/8953501b-c1c2-491e-ad80-92d41f407e31)

Compiled using ```cargo build --release --target x86_64-unknown-linux-gnu```

When executing the generated binary on a computer with PopOS 22.04, the texts do not render, but every update of the app continues normally, it is even possible to see that the element was added to my table
![popos_22_04_luis](https://github.com/iced-rs/iced/assets/14854891/3a99b01a-6586-46e9-a9f3-4a01f90a1dd8)

My Cargo.toml
```toml
[package]
name = "costv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["lazy"] }
iced_core = "0.12.3"

[profile.release]
strip = true
```

### What is the expected behavior?

This is the expected result

![Screenshot 2024-04-02 21 57 56](https://github.com/iced-rs/iced/assets/14854891/49ae364c-1d84-4cff-9efb-fd2af6bfe33c)

### Version

crates.io release

### Operating System

Linux
