### ISSUE TITLE
GLIBC_2.29 not found in Deepin 20.9

### ISSUE THREAD

**Issue by soucosmo** [iced-rs/iced#2368]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I get this error when trying to open in deepin 20.09

Compiled using ```cargo build --release --target x86_64-unknown-linux-gnu```

My development environment
![Screenshot 2024-04-02 22 04 56](https://github.com/iced-rs/iced/assets/14854891/131a3632-efc9-4d15-93aa-cd2300ad10f3)

When running the generated binary I get the following error
![imagem_deepin_20_9_mag](https://github.com/iced-rs/iced/assets/14854891/d69aa2ed-e3f6-44a6-96af-9458da842d96)

My Cargo.toml
```toml
[package]
name = "costv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["lazy"] }
iced_core = "0.12.3"

[profile.release]
strip = true
```

### What is the expected behavior?

This is the expected result

![Screenshot 2024-04-02 21 57 56](https://github.com/iced-rs/iced/assets/14854891/8bcd9159-eb4f-4527-839f-30d15b458550)

### Version

crates.io release

### Operating System

Linux
