### ISSUE TITLE
Application does not start on Windows 10 pro 64 bits

### ISSUE THREAD

**Issue by soucosmo** [iced-rs/iced#2369]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When running the application on Windows 10 Pro 64 bits I get the following behavior, a prompt window opens for a few seconds, and then it closes, as shown in the video below

https://github.com/iced-rs/iced/assets/14854891/ea883e0c-ec51-4670-85cc-d0e5b2edecf3

My development environment
![Screenshot 2024-04-02 22 04 56](https://github.com/iced-rs/iced/assets/14854891/074dca6f-a30b-4fda-b025-8b7e0c6b0077)

Compiled using ```cargo build --release --target x86_64-pc-windows-gnu```

My Cargo.toml
```toml
[package]
name = "costv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["lazy"] }
iced_core = "0.12.3"

[profile.release]
strip = true
```

### What is the expected behavior?

This is the expected behavior
![Screenshot 2024-04-02 21 57 56](https://github.com/iced-rs/iced/assets/14854891/39a25505-2361-401f-8331-7a35f7073736)

### Version

crates.io release

### Operating System

Windows
