### ISSUE TITLE
Shell opens along with the iced application in Windows 11 Pro

### ISSUE THREAD

**Issue by soucosmo** [iced-rs/iced#2370]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When running on Windows 11 Pro, a shell window opens, and the same window remains open throughout the execution of my application
![WhatsApp Image 2024-04-02 at 10 53 49 PM](https://github.com/iced-rs/iced/assets/14854891/ad62d263-7477-47d6-bf47-4701a7bea30e)

Compiled using ```cargo build --release --target x86_64-pc-windows-gnu```

My development environment
![Screenshot 2024-04-02 22 04 56](https://github.com/iced-rs/iced/assets/14854891/b81219bd-f9e1-4048-9159-9186da43375d)

My Cargo.toml
```toml
[package]
name = "costv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["lazy"] }
iced_core = "0.12.3"

[profile.release]
strip = true
```

### What is the expected behavior?

I believe the shell window should not be displayed, this only happens on windows, on linux the application runs without the terminal window

### Version

crates.io release

### Operating System

Windows
