### ISSUE TITLE
Update the documents

### ISSUE THREAD

**Issue by rawhuul** [iced-rs/iced#2515]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

The [doc.rs](https://docs.rs/iced/latest/iced/widget/trait.Component.html) page shows their is `Component` trait in `iced::widget` module, however it is not present in module and even getting docs from `cargo doc --open`, doesn't show the trait.

My `Cargo.toml` is:
```toml
[package]
name = "abc"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["tokio", "advanced"] }
tokio = { version = "1.38.1", features = ["full"] }
```

### What is the expected behavior?

Is `Container` trait deprecated? If not, in which module it is located?

### Version

crates.io release

### Operating System

Windows
